/*
 * Copyright 2026 Duck Apps Contributor
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */

package com.dchecker.info.core.ui.components

import androidx.compose.runtime.staticCompositionLocalOf

/**
 * Home-only presentation translations. Detector models, sorting, evidence, and exported reports
 * retain their original values. Match complete phrases so paths, package names, property values,
 * and other raw evidence are never translated by accident.
 */
val LocalHomeChinese = staticCompositionLocalOf { false }

object HomeChineseText {
    private val exact = mapOf(
        // Overview, actions, and detector names.
        "Build Time (UTC)" to "构建时间（UTC）",
        "Export Report" to "导出报告",
        "Running local checks" to "正在运行本地检测",
        "Dashboard summary will unlock when the detector cards finish collecting evidence." to "检测卡片收集完证据后，将显示首页汇总。",
        "Security overview" to "安全概览",
        "Danger" to "危险",
        "Warning" to "警告",
        "Info" to "信息",
        "Ready" to "已完成",
        "Pending" to "等待中",
        "OK" to "正常",
        "High" to "高风险",
        "Warn" to "警告",
        "Check" to "待核查",
        "Clear" to "正常",
        "Top findings" to "重点发现",
        "Priority review queue" to "优先核查项目",
        "Scan status" to "扫描状态",
        "Overview" to "概览",
        "Waiting for detector evidence" to "等待检测证据",
        "No urgent findings in ready modules" to "已完成项目中无紧急发现",
        "Detector cards will expand as modules finish collecting local evidence." to "各模块收集完本地证据后会展开检测卡片。",
        "Detector cards will populate as local checks complete." to "本地检测完成后将显示检测卡片。",
        "Additional modules are still collecting their local evidence." to "部分模块仍在收集本地证据。",
        "Use the detector cards below to inspect local evidence in detail." to "请在下方检测卡片中查看本地证据。",
        "Open detector cards below to review detailed local evidence and secondary checks." to "展开下方检测卡片，查看详细证据及补充检查。",
        "Bootloader" to "引导加载程序",
        "Mount" to "挂载环境",
        "Memory" to "进程内存",
        "LSPosed" to "LSPosed",
        "SELinux" to "SELinux",
        "Dangerous Apps" to "风险应用",
        "Play Integrity Fix" to "Play Integrity Fix",
        "Native Root" to "原生 Root",
        "TEE" to "TEE 安全环境",
        "SU" to "SU 权限",
        "Custom ROM" to "第三方 ROM",
        "Kernel Check" to "内核检测",
        "System Properties" to "系统属性",
        "Virtualization" to "虚拟化",
        "Zygisk" to "Zygisk",
        "Device Info" to "设备信息",
        "Device info" to "设备信息",
        "attestation + boot props + DRM consistency" to "认证 + 启动属性 + DRM 一致性",
        "local bootloader scan failed" to "本地引导加载程序扫描失败",
        "properties + prop integrity + packages + services + native traces" to "属性 + 属性完整性 + 应用包 + 服务 + 原生痕迹",
        "local aftermarket firmware probe failed" to "本地第三方固件检测失败",
        "identity + build + android + runtime + display" to "身份 + 构建信息 + Android + 运行环境 + 显示信息",
        "local device profile unavailable" to "本地设备信息不可用",
        "uname + /proc/version + boot cmdline + CVE heuristic" to "uname + /proc/version + 启动参数 + CVE 启发式检查",
        "local kernel probe failed" to "本地内核检测失败",
        "class + classloader + bridge fields + callbacks + runtime + logcat + binder + zygote gids + policy + native" to "类 + 类加载器 + 桥接字段 + 回调 + 运行环境 + logcat + Binder + Zygote GID + 策略 + 原生检测",
        "local LSPosed/Xposed scan failed" to "本地 LSPosed/Xposed 扫描失败",
        "function entry + maps/smaps + fd + signal + linker" to "函数入口 + maps/smaps + 文件描述符 + 信号 + 链接器",
        "local native probe failed" to "本地原生检测失败",
        "6 native detector families · current-process memory only" to "6 类原生检测 · 仅检查当前进程内存",
        "mounts + mountinfo + maps + statfs + statx" to "挂载 + mountinfo + 内存映射 + statfs + statx",
        "local mount scan failed" to "本地挂载扫描失败",
        "supercall + prctl + setresuid + runtime paths + /proc + isolated mount" to "超级调用 + prctl + setresuid + 运行时路径 + /proc + 隔离挂载",
        "native root scan failed" to "原生 Root 扫描失败",
        "native detector unavailable" to "原生检测不可用",
        "multi-source props + native libc + runtime maps" to "多来源属性 + 原生 libc + 运行时内存映射",
        "local Play Integrity residue scan failed" to "本地 Play Integrity 残留扫描失败",
        "sysfs + getenforce + proc attr + app_zygote zygotePreload seqno + context oracle + policy + audit" to "sysfs + getenforce + 进程属性 + app_zygote 预加载序列 + 上下文验证 + 策略 + 审计",
        "local status probe failed" to "本地状态检测失败",
        "su paths + PATH + adb daemons + native context" to "su 路径 + PATH + adb 守护进程 + 原生上下文",
        "local root probe failed" to "本地 Root 检测失败",
        "security props + raw boot + source cross-checks" to "安全属性 + 原始启动信息 + 多来源交叉核验",
        "local property scan failed" to "本地属性扫描失败",
        "properties + build + runtime artifacts + helper process + honeypots" to "属性 + 构建信息 + 运行时痕迹 + 辅助进程 + 陷阱检测",
        "local virtualization scan failed" to "本地虚拟化扫描失败",
        "cross-process fd trap + linker/maps/heap/seccomp/runtime" to "跨进程文件描述符陷阱 + 链接器/映射/堆/seccomp/运行环境",
        "zygote injection scan failed" to "Zygote 注入扫描失败",

        // Kotlin-generated Home strings that do not come from Android resources.
        "Gathering attestation, verified-boot, and property consistency evidence." to "正在收集设备认证、验证启动与属性一致性证据。",
        "Bootloader scan failed before evidence could be assembled." to "在完成证据整理前，引导加载程序检测已失败。",
        "Attestation RootOfTrust, certificate trust, boot properties, raw androidboot parameters, and Widevine credential consistency checks are collecting local evidence." to "正在收集 RootOfTrust 认证、证书信任、启动属性、原始 androidboot 参数和 Widevine 凭据一致性证据。",
        "System properties, prop integrity, runtime packages/services, framework traces, and resource map checks are collecting local firmware evidence." to "正在收集系统属性、属性完整性、运行时应用/服务、框架痕迹和资源映射等本地固件证据。",
        "Custom ROM scan failed before evidence could be assembled." to "在完成证据整理前，第三方 ROM 检测已失败。",
        "Build properties, property-area integrity, bootloader state, runtime packages or services, framework traces, native symbol traces, or resource map anomalies indicate aftermarket firmware, resetprop-style changes, or an unlocked boot chain." to "构建属性、属性区完整性、引导加载程序状态、运行时应用或服务、框架痕迹、原生符号痕迹或资源映射异常，可能表明存在第三方固件、resetprop 类修改或已解锁的启动链。",
        "No common custom ROM branding, property-area, service, package, framework trace, native symbol trace, or resource map anomaly surfaced from local probes." to "本地探针未发现常见第三方 ROM 品牌、属性区、服务、应用包、框架痕迹、原生符号痕迹或资源映射异常。",
        "Native property-area coverage was unavailable on this build." to "当前构建无法进行原生属性区检查。",
        "Native symbol trace detection only runs on Android 10+." to "原生符号痕迹检测仅支持 Android 10 及以上版本。",
        "Gathering local firmware branding and framework evidence." to "正在收集本地固件品牌和框架证据。",
        "Aftermarket firmware can legitimately alter build properties, property storage, bootloader state, privileged services, and security defaults." to "第三方固件可能会正常修改构建属性、属性存储、引导加载程序状态、特权服务以及安全默认值。",
        "Attestation behavior, Play Integrity, and some banking or DRM apps may differ on custom ROMs or modified boot chains." to "在第三方 ROM 或已修改的启动链上，设备认证、Play Integrity 以及部分银行或 DRM 应用的行为可能不同。",
        "This signal alone does not prove malicious compromise or active root access." to "仅凭这一信号不能证明设备遭到恶意入侵或当前存在 Root 权限。",
        "Native coverage was unavailable on this build, so clean native trace results are not available." to "当前构建无法进行原生检测，因此不能得到原生痕迹的正常结论。",
        "No common aftermarket firmware branding, property-area, or framework traces were found." to "未发现常见第三方固件品牌、属性区或框架痕迹。",
        "Package visibility was scoped, so clean app-level evidence may be incomplete." to "应用可见性受到限制，因此应用层的正常结果可能不完整。",
        "A determined ROM can remove obvious signatures, so absence is not proof of stock firmware." to "经过针对性隐藏的 ROM 可以移除明显特征，因此未发现特征并不能证明设备运行原厂固件。",
        "Native framework trace coverage was unavailable on this build." to "当前构建无法进行原生框架痕迹检测。",
        "This detector checks symbol resolution, function entry bytes, executable mappings, suspicious memfd or deleted libraries, signal handlers, and loader visibility." to "此检测器会检查符号解析、函数入口字节、可执行内存映射、可疑 memfd 或已删除库、信号处理器以及加载器可见性。",
        "Memory detection failed before native evidence could be assembled." to "在完成原生证据整理前，内存检测已失败。",
        "High-risk findings point to hook-like code redirection, suspicious executable mappings, or loader-visible runtime artifacts." to "高风险发现通常指向类似 Hook 的代码重定向、可疑可执行内存映射或加载器可见的运行时痕迹。",
        "Native memory evidence was unavailable, so this card cannot treat the absence of findings as a clean runtime result." to "原生内存证据不可用，因此不能把“未发现异常”视为运行环境正常。",
        "No suspicious evidence surfaced in this memory slice." to "当前内存检查范围内未发现可疑证据。",
        "Native memory evidence was unavailable, so this slice could not be verified." to "原生内存证据不可用，因此无法验证此检查范围。",
        "Gathering local runtime memory evidence." to "正在收集本地运行时内存证据。",
        "Hook-like entry changes, deleted executable loaders, or anonymous signal handlers are stronger runtime tampering signals than filesystem-only artifacts." to "类似 Hook 的函数入口改动、已删除的可执行加载项或匿名信号处理器，比单纯的文件系统痕迹更能说明运行时可能被修改。",
        "This card only sees the current app process, so it should be read together with mount, SU, kernel, and TEE evidence." to "此卡片只能查看当前应用进程，应结合挂载、SU、内核和 TEE 证据一起判断。",
        "The findings here are weaker than a direct hook or deleted loader hit, but they still mean the runtime view is not fully boring." to "这里的发现弱于直接 Hook 或已删除加载项命中，但仍说明运行时环境存在值得核查的异常。",
        "Review findings often come from mapping hygiene, loader visibility, or vDSO consistency rather than a direct redirection primitive." to "待核查项通常来自内存映射、加载器可见性或 vDSO 一致性，而不一定是直接的代码重定向。",
        "The current process did not expose branch-heavy function entries, suspicious executable memfd paths, or loader visibility mismatches." to "当前进程未发现异常分支密集的函数入口、可疑可执行 memfd 路径或加载器可见性不一致。",
        "Native memory evidence was unavailable, so this support-only result should not be treated as clean." to "原生内存证据不可用，因此此辅助结果不能视为正常。",
        "A clean memory slice reduces confidence in in-process runtime hooking only when the native probe ran successfully." to "只有原生探针成功运行时，正常的内存检查结果才能降低当前进程存在运行时 Hook 的可能性。",
        "Mount table, mountinfo, memory maps, filesystem type, and path-based root artifact probes are collecting local evidence." to "正在从挂载表、mountinfo、内存映射、文件系统类型和基于路径的 Root 痕迹探针收集本地证据。",
        "Mount scan failed before evidence could be assembled." to "在完成证据整理前，挂载检测已失败。",
        "Startup preload captured early namespace or mount anomalies before the normal runtime scan settled." to "启动预加载在常规运行时扫描稳定前捕获到了早期命名空间或挂载异常。",
        "Startup preload captured weaker early mount inconsistencies that still merit review." to "启动预加载捕获到了较弱的早期挂载不一致，仍建议核查。",
        "The current app mount view contains root-managed overlays, writable-system behavior, selective shell-tmp concealment, hidden mount inconsistencies, or strong runtime artifacts." to "当前应用的挂载视图中发现 Root 管理的 overlay、系统可写行为、选择性 shell 临时目录隐藏、挂载不一致或明显运行时痕迹。",
        "Gathering runtime mount and filesystem evidence." to "正在收集运行时挂载和文件系统证据。",
        "A direct root token in a visible process mount table is strong evidence of a root-managed mount layer." to "可见进程挂载表中的直接 Root 标记，是 Root 管理挂载层的强证据。",
        "Different processes expose different mount tables to the isolated observer, which can indicate selective mount hiding." to "不同进程向隔离观察者暴露了不同的挂载表，这可能表明存在选择性挂载隐藏。",
        "The isolated helper process did not return cross-process mount view data." to "隔离辅助进程未返回跨进程挂载视图数据。",
        "Mappings" to "内存映射",
        "Hardware-backed" to "硬件支持",
        "Reflection API" to "反射 API",
        "getprop snapshot" to "getprop 快照",
        "Native libc" to "原生 libc",
        "Raw boot params" to "原始启动参数",
        "Source consistency" to "来源一致性",
        "Attest" to "认证",
        "Props" to "属性",
        "Verified" to "已验证",
        "Custom" to "自定义",
        "Unlocked" to "已解锁",
        "Locked?" to "疑似锁定",
        "Software" to "软件级",
        "Factory" to "厂商",
        "Build fields" to "构建字段",
        "Modification" to "修改项",
        "Services" to "服务",
        "Reflection" to "反射",
        "Resource maps" to "资源映射",
        "Platform files" to "平台文件",
        "Recovery scripts" to "Recovery 脚本",
        "Product overlays" to "产品 Overlay",
        "Build fields checked" to "已检查构建字段",
        "Modification props checked" to "已检查修改属性",
        "Prop area contexts" to "属性区上下文",
        "Prop item anomalies" to "属性项异常",
        "Named services checked" to "已检查命名服务",
        "Services listed" to "已列出服务",
        "GOT/PLT resolution" to "GOT/PLT 解析",
        "Entry prologue" to "函数入口序言",
        "maps + smaps" to "maps + smaps",
        "FD-backed code" to "FD 支持的代码",
        "KSU mount" to "KSU 挂载",
        "Magisk mount" to "Magisk 挂载",
        "Root mount" to "Root 挂载",
        "Fresh" to "有效",
        "Stale" to "已过期",
        "Startup preload" to "启动预加载",
        "Preload context" to "预加载上下文",
        "Preload findings" to "预加载发现",
        "Map lines" to "内存映射行数",
        "Maps readable" to "内存映射可读取",
        "statx support" to "statx 支持",
        "Path probes" to "路径探针",
        "Shell tmp view" to "Shell 临时目录视图",
        "Filesystem probes" to "文件系统探针",
        "statx cross-check" to "statx 交叉核验",

        // Shared card sections and short result values.
        "State" to "状态",
        "Security state" to "安全状态",
        "Scan State" to "扫描状态",
        "Security and runtime" to "安全与运行环境",
        "Security spoof" to "安全信息伪装",
        "Status" to "状态",
        "Mode" to "模式",
        "Proof" to "证据",
        "Tier" to "安全级别",
        "Trust" to "信任状态",
        "Trust root" to "信任根",
        "Confidence" to "可信度",
        "Coverage" to "覆盖情况",
        "Critical" to "严重",
        "Review" to "待核查",
        "Clean" to "未发现异常",
        "All clear" to "未发现异常",
        "Failed" to "失败",
        "Error" to "错误",
        "Unavailable" to "不可用",
        "Unknown" to "未知",
        "None" to "无",
        "Yes" to "是",
        "No" to "否",
        "N/A" to "不适用",
        "Loaded" to "已加载",
        "Not observed" to "未观察到",
        "Not resolved yet" to "尚未得到结果",
        "Unsupported" to "不支持",
        "Blocked by seccomp" to "被 seccomp 阻止",
        "Permission denied" to "权限不足",
        "Limited" to "覆盖受限",
        "Captured" to "已获取",
        "Full" to "完整",
        "Scoped" to "受限",
        "Listed" to "已列出",
        "Readable" to "可读取",
        "Unreadable" to "不可读取",
        "Detected" to "已检测到",
        "No signal" to "未发现信号",
        "Strong signals" to "强信号",
        "Heuristic signals" to "启发式信号",
        "Review signals" to "待核查信号",
        "Danger signals" to "危险信号",
        "Signals" to "检测信号",
        "Signal summary" to "信号汇总",
        "Impact" to "可能影响",
        "References" to "参考资料",
        "Detection methods" to "检测方法",
        "Detection Methods" to "检测方法",
        "Detection path" to "检测路径",
        "Evidence source" to "证据来源",
        "Direct confirmation" to "直接证据",
        "Fallback inference" to "补充推断",
        "Context" to "上下文",
        "Runtime" to "运行时",
        "Native" to "原生检测",
        "Packages" to "应用包",
        "Properties" to "属性",
        "Build" to "构建信息",
        "Boot" to "启动状态",
        "Kernel" to "内核",
        "Flags" to "标志",
        "Direct" to "直接证据",
        "Hooks" to "Hook",
        "Targets" to "目标",
        "Hits" to "命中",
        "Hidden" to "已隐藏",
        "PM" to "软件包管理器",
        "Host" to "宿主",
        "ROMs" to "ROM",
        "Identity" to "标识",
        "Behavior" to "行为",
        "Anomalies" to "异常",
        "Artifacts" to "痕迹",
        "Daemons" to "守护进程",
        "Processes" to "进程",
        "Policy" to "安全策略",
        "Audit" to "审计",
        "Certificates" to "证书",
        "Certificate chain" to "证书链",
        "Network" to "网络",
        "Scan summary" to "扫描汇总",
        "Device profile unavailable" to "设备资料不可用",
        "Unknown error" to "未知错误",
        "No findings were produced for this section." to "本节未发现可显示的结果。",
        "No rows were produced for this section on this device." to "此设备上本节没有可显示的检测项。",

        // Card verdicts and explanations shown on Home.
        "Scanning boot state and verified boot evidence" to "正在检查启动状态与验证启动证据",
        "Bootloader scan failed" to "引导加载程序检测失败",
        "Locked and attested verified" to "设备已锁定，认证结果显示验证启动正常",
        "Locked by boot properties" to "启动属性显示设备已锁定",
        "Locked state without full proof" to "设备显示已锁定，但证据不足",
        "Boot state inconclusive" to "启动状态无法确定",
        "Attestation and boot properties stayed aligned with a locked, verified boot chain." to "认证与启动属性一致，均显示已锁定且验证启动正常。",
        "Boot properties look conservative, but the result falls back to software-readable signals because attestation RootOfTrust was unavailable." to "启动属性未见明显异常，但无法取得 RootOfTrust 认证，只能依据软件可读信息判断。",
        "Neither attestation RootOfTrust nor readable boot properties exposed enough data for a confident bootloader verdict." to "RootOfTrust 认证与可读启动属性均不足，无法可靠判断引导加载程序状态。",
        "The boot chain is not obviously broken, but custom-root, software-only, Widevine DRM, or cross-source coherence signals still need review." to "启动链未见明显破坏，但自定义信任根、软件级认证、Widevine DRM 或多来源一致性仍需核查。",
        "Unlocked state, attestation contradictions, broken certificate trust, verified-boot failures, or a corroborated Widevine DRM inconsistency indicate reduced device trust." to "解锁状态、认证矛盾、证书信任异常、验证启动失败或 Widevine DRM 不一致会降低设备可信度。",
        "Scanning runtime mount visibility" to "正在检查运行时挂载视图",
        "No suspicious mount-layer signal" to "未发现可疑挂载信号",
        "A visible process mount table contains a direct root-managed mount token." to "可见进程的挂载表包含由 Root 工具管理的直接痕迹。",
        "Cross-process mount tables diverge from the isolated-process baseline." to "不同进程的挂载表与隔离进程基线不一致。",
        "The mount layer is not obviously compromised, but it still contains review-worthy runtime or filesystem drift." to "挂载层未见明确异常，但运行时或文件系统差异仍需核查。",
        "No suspicious Magisk, overlay, writable-system, or mount-coherence artifact surfaced from the current app context." to "当前应用环境中未发现可疑的 Magisk、overlay、系统可写或挂载一致性痕迹。",
        "Scanning runtime memory" to "正在检查运行时内存",
        "Runtime memory needs review" to "运行时内存需要核查",
        "Memory scan has reduced native coverage" to "内存扫描的原生检测覆盖受限",
        "No hook-like memory signals" to "未发现类似 Hook 的内存信号",
        "No hook-style prologue changes, suspicious executable memfd paths, or loader visibility mismatches surfaced." to "未发现类似 Hook 的函数入口改动、可疑可执行 memfd 路径或加载器可见性差异。",
        "The current process memory stayed mostly clean, but there are still runtime indicators that deserve review." to "当前进程内存总体正常，但仍有运行时指标需要核查。",
        "Scanning LSPosed/Xposed runtime and residue" to "正在检查 LSPosed/Xposed 运行时及残留",
        "Dirty SELinux policy exposes LSPosed rule" to "SELinux 策略暴露了 LSPosed 规则",
        "Dirty SELinux policy signal(s)" to "发现 SELinux 策略异常信号",
        "LSPosed scan has reduced coverage" to "LSPosed 检测覆盖受限",
        "No LSPosed/Xposed runtime signal" to "未发现 LSPosed/Xposed 运行时信号",
        "No Xposed class loading, ClassLoader, callback, Binder bridge, runtime artifact, logcat, stack, maps, or heap traces surfaced in the current app process." to "当前应用进程中未发现 Xposed 类加载、回调、Binder 桥接、运行时痕迹或相关内存映射。",
        "No LSPosed/Xposed signal surfaced from the available probes, but at least one runtime, package, logcat, or native evidence path was unavailable." to "可用探针未发现 LSPosed/Xposed 信号，但部分运行时、应用包、日志或原生证据路径不可用。",
        "Scanning SELinux state" to "正在检查 SELinux 状态",
        "Enforcing" to "强制模式",
        "Permissive" to "宽松模式",
        "Disabled" to "已禁用",
        "Enforcing with audit rewrite" to "强制模式，审计日志疑似被改写",
        "Enforcing with KSU context materialized" to "强制模式，发现 KSU 上下文",
        "Enforcing with app_zygote seqno split" to "强制模式，app_zygote 序号不一致",
        "Enforcing with app_zygote attr-write anomaly" to "强制模式，app_zygote 属性写入异常",
        "Enforcing with untrusted app_zygote carrier" to "强制模式，app_zygote 载体不可信",
        "Enforcing with reduced app_zygote coverage" to "强制模式，app_zygote 检测覆盖受限",
        "Enforcing with unstable context oracle" to "强制模式，上下文探针结果不稳定",
        "Enforcing with untrusted context oracle" to "强制模式，上下文探针不可信",
        "Enforcing with context split" to "强制模式，上下文结果不一致",
        "Enforcing with audit exposure" to "强制模式，审计信息可见",
        "Enforcing with weak policy" to "强制模式，安全策略薄弱",
        "Enforcing with audit risk" to "强制模式，审计存在风险",
        "Enforcing with policy drift" to "强制模式，策略存在偏差",
        "Enforcing with minor drift" to "强制模式，存在轻微偏差",
        "SELinux is enforcing and the visible policy surface looks internally consistent." to "SELinux 处于强制模式，可见的策略检查结果一致。",
        "SELinux is enforcing and only minor policy drift surfaced." to "SELinux 处于强制模式，仅发现轻微策略差异。",
        "SELinux is enforcing, but policy analysis found noticeable drift." to "SELinux 处于强制模式，但策略分析发现明显偏差。",
        "SELinux is enforcing, but the policy looks severely weakened or modified." to "SELinux 处于强制模式，但策略疑似被严重削弱或修改。",
        "Scanning app inventory" to "正在扫描应用清单",
        "Inventory scan failed" to "应用清单扫描失败",
        "Shared storage baseline denied" to "共享存储基线访问被拒",
        "Package inventory unusually small" to "可见应用清单异常偏少",
        "Inventory visibility limited" to "应用清单可见性受限",
        "No known risky packages" to "未发现已知风险应用",
        "No direct virtualization signal" to "未发现直接虚拟化信号",
        "No native root indicators" to "未发现原生 Root 指标",
        "No root indicators" to "未发现 Root 指标",
        "No root indicators from available probes" to "可用探针未发现 Root 指标",
        "No Play Integrity residue surfaced" to "未发现 Play Integrity 绕过残留",
        "No Zygisk runtime signal" to "未发现 Zygisk 运行时信号",
        "No risky property or coherence drift" to "未发现可疑属性或一致性差异",
        "No suspicious kernel markers" to "未发现可疑内核标记",
        "No custom ROM signatures" to "未发现第三方 ROM 特征",
        "No direct virtualization signal surfaced from available probes, but coverage was incomplete." to "可用探针未发现直接虚拟化信号，但检测覆盖不完整。",
        "No common SU binaries or adb root daemons surfaced." to "未发现常见 SU 可执行文件或 adb Root 守护进程。",
        "Common su binaries, adb daemons, and native SELinux context probes stayed clean." to "常见 su 文件、adb 守护进程及原生 SELinux 上下文探针均未发现异常。",
        "Scanning Play Integrity residue" to "正在检查 Play Integrity 绕过残留",
        "Scanning kernel-root indicators" to "正在检查内核级 Root 指标",
        "Scanning root artifacts" to "正在检查 Root 痕迹",
        "Scanning kernel identity" to "正在检查内核标识",
        "Scanning property, boot, and source state" to "正在检查属性、启动和来源状态",
        "Scanning Zygisk runtime traces" to "正在检查 Zygisk 运行时痕迹",
        "Scanning virtualization and translation state" to "正在检查虚拟化和转译状态",
        "Scanning aftermarket firmware signals" to "正在检查第三方固件特征",
        "Collecting local device profile" to "正在收集本地设备资料",
        "Have a good day" to "祝你今天愉快",
        "This card is informational only. It gives you a fixed local profile snapshot to read alongside the detector cards above." to "此卡片仅提供设备信息快照，可与上方检测卡片一起参考。",
        "This card is purely contextual and does not affect detector severity or ranking." to "此卡片仅提供背景信息，不影响检测风险等级或排序。",
        "Cross-process FD trap is positive" to "跨进程 FD 陷阱检测为阳性",
        "One heuristic probe needs review" to "一项启发式探针需要核查",
        "Zygisk result needs more support" to "Zygisk 检测结果需要更多证据",
        "LSPosed scan failed" to "LSPosed 扫描失败",
        "Zygisk scan failed" to "Zygisk 扫描失败",
        "SU scan failed" to "SU 扫描失败",
        "Kernel Check scan failed" to "内核扫描失败",
        "System Properties scan failed" to "系统属性扫描失败",
        "Virtualization scan failed" to "虚拟化扫描失败",
        "Custom ROM scan failed" to "第三方 ROM 扫描失败",
        "Play Integrity Fix scan failed" to "Play Integrity Fix 扫描失败",
        "Native Root scan failed" to "原生 Root 扫描失败",
        "Memory scan failed" to "内存扫描失败",
        "Mount scan failed" to "挂载环境扫描失败",
        "SELinux scan failed" to "SELinux 扫描失败",
        "Root indicators detected" to "检测到 Root 指标",
        "Abnormal root context detected" to "检测到异常 Root 上下文",
        "SU binary detected" to "检测到 SU 可执行文件",
        "Temp root exploit (CVE-2026-43499) detected" to "检测到临时 Root 漏洞利用（CVE-2026-43499）",
        "Temp root artifacts detected in /data/local/tmp" to "在 /data/local/tmp 中发现临时 Root 痕迹",
        "KernelSU and APatch indicators detected" to "检测到 KernelSU 与 APatch 指标",
        "Current app already runs in KernelSU su domain" to "当前应用已运行于 KernelSU su 域",
        "KernelSU detected via ksu_driver" to "通过 ksu_driver 检测到 KernelSU",
        "KernelSU detected via prctl" to "通过 prctl 检测到 KernelSU",
        "KernelSU indicators detected" to "检测到 KernelSU 指标",
        "APatch indicators detected" to "检测到 APatch 指标",
        "Magisk native indicators detected" to "检测到 Magisk 原生指标",
        "Isolated mount drift suggests namespace tampering" to "隔离进程挂载差异提示命名空间可能被修改",
        "Isolated-process namespace drift needs review" to "隔离进程命名空间差异需要核查",
        "KernelSU manager weak fingerprint detected" to "检测到 KernelSU 管理器的弱特征",
        "KernelSU manager package detected" to "检测到 KernelSU 管理器应用包",
        "Native detector unavailable" to "原生探针不可用",
        "Native root scan has reduced coverage" to "原生 Root 检测覆盖受限",
        "Kernel behavior needs review" to "内核行为需要核查",
        "CVE patch state is informational" to "CVE 修复状态仅供参考",
        "CVE patch state inconclusive" to "无法确定 CVE 修复状态",
        "Kernel scan has reduced native coverage" to "内核原生检测覆盖受限",
        "System property scan has reduced coverage" to "系统属性检测覆盖受限",
        "Virtualization scan has reduced coverage" to "虚拟化检测覆盖受限",
        "Custom ROM scan has reduced coverage" to "第三方 ROM 检测覆盖受限",
        "Play Integrity scan has reduced native coverage" to "Play Integrity 原生检测覆盖受限",
        "HMA-style concealment detected" to "检测到 HMA 类隐藏行为",
        "No common aftermarket firmware branding, property-area, or framework traces were found." to "未发现常见第三方固件标识、属性区或框架痕迹。",
        "No common custom ROM branding, property-area, service, package, framework trace, native symbol trace, or resource map anomaly surfaced from local probes." to "本地探针未发现常见第三方 ROM 标识、属性区、服务、应用包、框架、原生符号或资源映射异常。",
        "No direct emulator, AVF guest, native-bridge, or cross-process drift artifact surfaced from the current app context." to "当前应用环境中未发现直接模拟器、AVF 客体、原生桥接或跨进程差异痕迹。",
        "No catalogued Play Integrity residue property or runtime trace was observed across reflection, getprop, native libc, and maps checks." to "反射、getprop、原生 libc 和内存映射检查均未发现已收录的 Play Integrity 绕过残留。",
        "No direct runtime or converging heuristic signal surfaced in the current app process." to "当前应用进程中未发现直接运行时信号或相互印证的启发式信号。",
        "The FD trap stayed clean and the native runtime snapshot did not expose TMP_PATH, linker, maps, heap, thread, or descriptor traces associated with Zygisk-style injection." to "FD 陷阱及原生运行时快照未发现与 Zygisk 类注入有关的 TMP_PATH、链接器、内存映射、堆、线程或描述符痕迹。",
        "Only heuristic residue surfaced, so this result should be read together with Memory and Mount before treating it as a confirmed Zygisk runtime." to "仅发现启发式残留，应结合内存和挂载检测，不能直接认定 Zygisk 运行时存在。",
        "FD trap or direct runtime probes exposed evidence consistent with TMP_PATH leakage, specialization tampering, namespace bypass, linker redirection, ptrace attachment, or libc-hook side effects." to "FD 陷阱或直接运行时探针发现了 TMP_PATH 泄露、进程特化篡改、命名空间绕过、链接器重定向、ptrace 附加或 libc Hook 的相关证据。",
        "One or more major scan paths were unavailable, so this card cannot treat the absence of hits as a clean runtime result." to "一个或多个重要扫描路径不可用，不能将没有命中视为运行时完全正常。",
        "No common Play Integrity Fix residue surfaced from the current property catalog or runtime trace heuristics." to "属性目录和运行时痕迹探针未发现常见 Play Integrity Fix 残留。",
        "Direct spoof properties or runtime traces suggest active or recently used Play Integrity bypass infrastructure." to "直接伪装属性或运行时痕迹提示 Play Integrity 绕过组件正在使用或近期曾使用。",
        "Only lower-confidence residue or cross-source drift surfaced. This can reflect disabled leftovers, partial cleanup, or source disagreement." to "仅发现可信度较低的残留或多来源差异，可能是禁用后的痕迹、清理不完整或来源不一致。",
        "Observed key properties matched conservative production expectations across multiple read paths." to "关键属性在多条读取路径上的结果与常规量产设备预期一致。",
        "Key properties, framework constants, native libc reads, raw boot parameters, and property-area layout stayed aligned." to "关键属性、框架常量、原生 libc 读取值、原始启动参数及属性区布局相互一致。",
        "Cross-source drift, cross-property drift, or raw property-area residue suggests a review-worthy build or boot context, even if not every warning means active compromise." to "多来源或多属性差异、原始属性区残留提示构建或启动环境需要核查，但警告不一定代表正在被篡改。",
        "The current app context contains direct emulator, AVF guest, device-node, classpath, UID, or runtime-service evidence." to "当前应用环境中发现模拟器、AVF 客体、设备节点、类路径、UID 或运行时服务的直接证据。",
        "The app is not conclusively inside a guest, but translation, renderer, classpath drift, consistency drift, or honeypot anomalies still require review." to "无法确定应用是否位于虚拟客体内，但转译层、渲染器、类路径、一致性或蜜罐探针异常仍需核查。",
        "Known virtualization host apps are present on the device, but current process probes did not confirm guest execution." to "设备中存在已知虚拟化宿主应用，但当前进程探针未确认客体运行。",
        "No hard kernel naming marker surfaced from fallback identity reads, but native-only /proc checks were unavailable on this build." to "备用内核标识读取未发现明确标记，但此构建的原生 /proc 检查不可用。",
        "Kernel identity, boot parameters, and behavior heuristics stayed within expected bounds." to "内核标识、启动参数和行为探针均在预期范围内。",
        "Kernel behavior heuristics surfaced review-worthy signals, but they are weaker than direct naming or boot parameter anomalies." to "内核行为探针发现需要核查的信号，其可信度低于直接标识或启动参数异常。",
        "The Unicode path-bypass probe suggests CVE-2024-43093 is not fully patched, but this is informational context rather than a kernel-compromise signal." to "Unicode 路径绕过探针提示 CVE-2024-43093 可能未完全修复；这仅是参考信息，并不直接证明内核被篡改。",
        "The Unicode path-bypass probe could not determine whether CVE-2024-43093 is fully patched on this device." to "Unicode 路径绕过探针无法确定此设备是否已完整修复 CVE-2024-43093。",
        "No native root indicator surfaced from available probes, but one or more direct, cgroup, isolated-process, or package-visibility evidence paths had reduced coverage." to "可用探针未发现原生 Root 指标，但直接探针、cgroup、隔离进程或应用可见性检查存在覆盖不足。",
        "No common KernelSU, APatch, Magisk, SUSFS, or cgroup-leak traces surfaced from the current probe set." to "当前探针未发现常见 KernelSU、APatch、Magisk、SUSFS 或 cgroup 泄露痕迹。",
        "Native coverage was unavailable on this build, so only Java-side probes were used." to "当前构建缺少原生检测，因此仅使用 Java 侧探针。",
        "Available probes were clean, but package visibility, property-area, or native symbol coverage was incomplete on this build." to "可用探针未发现异常，但应用可见性、属性区或原生符号检测覆盖不完整。",
        // TEE report headlines and concise explanations.
        "Attestation aligned; local probes need review" to "认证结果一致，但本地探针需要核查",
        "Local TEE attestation checks aligned" to "本地 TEE 认证检查一致",
        "Policy-backed attestation anomalies were detected" to "检测到受策略保护的认证异常",
        "Policy-backed attestation evidence needs review" to "受策略保护的认证证据需要核查",
        "Hardware-backed local verification was not established" to "未建立硬件支持的本地验证",
        "Local verification stayed inconclusive" to "本地验证结果仍无法确定",
        "Attestation, trust path, and revocation checks line up." to "认证、信任路径和吊销检查结果一致。",
        "Attestation and trust-path checks still aligned." to "认证与信任路径检查仍保持一致。",
        "Multiple hard anomaly indicators were raised." to "发现多项高可信异常指标。",
        "Policy-backed review signals suggest further review." to "受策略保护的检查发现需要进一步核查的信号。",
        "Local verification could not establish hardware-backed trust." to "本地验证无法建立硬件支持的信任。",
        "Signals were mixed and did not converge on a stable local result." to "信号相互矛盾，无法得到稳定的本地结论。",
        "Collecting local attestation and keystore evidence." to "正在收集本地认证和密钥库证据。",
        "Local trust path pending" to "本地信任路径检查中",
        "Local trust path unavailable" to "本地信任路径不可用",
        "Local TEE verification failed" to "本地 TEE 验证失败",
        "Aligned • local review" to "结果一致 · 需本地核查",
        "Checks aligned" to "检查结果一致",
        "No hardware trust" to "无法建立硬件信任",
        "Mixed signals" to "信号不一致",
        "Scanning" to "扫描中",
        "Aligned + review" to "结果一致，仍需核查",
        "Aligned" to "结果一致",
        "Tampered" to "疑似被篡改",
        "Broken" to "验证失败",
        "Mixed" to "结果不一致",
        "Verdict" to "结论",
        "Score" to "评分",
        "Details" to "详情",
        "Checks" to "检查项目",
        "Collection failure" to "证据收集失败",
        "Attestation" to "设备认证",
        "Root fingerprint" to "根证书指纹",
        "Patch levels" to "补丁级别",
        "Key properties" to "密钥属性",
        "User auth" to "用户认证",
        "Application" to "应用信息",
        "Grant self-domain certificate chain diverged; open TEE details for stage diagnostics." to "自域授权的证书链不一致；请打开 TEE 详情查看各阶段诊断。",
        "Grant self-domain key visibility diverged; open TEE details for stage diagnostics." to "自域授权的密钥可见性不一致；请打开 TEE 详情查看各阶段诊断。",
        "Grant isolated-domain certificate chain diverged; open TEE details for stage diagnostics." to "隔离域授权的证书链不一致；请打开 TEE 详情查看各阶段诊断。",
        "Grant isolated-domain key visibility diverged; open TEE details for stage diagnostics." to "隔离域授权的密钥可见性不一致；请打开 TEE 详情查看各阶段诊断。",
        "Grant isolated-domain runtime crash; open TEE details for stage diagnostics." to "隔离域授权运行时崩溃；请打开 TEE 详情查看各阶段诊断。",
        "Grant handle caller binding failed; open TEE details for stage diagnostics." to "授权句柄的调用方绑定失败；请打开 TEE 详情查看各阶段诊断。",
        "Built-in revocation snapshot is active; online refresh is disabled in Settings." to "内置吊销快照正在使用；设置中已关闭在线刷新。",
        "Online revocation data refreshed successfully." to "在线吊销数据刷新成功。",
        "Online CRL refresh failed; built-in revocation snapshot was used." to "在线 CRL 刷新失败，已使用内置吊销快照。",

        // Common expanded-card labels. Keep implementation identifiers and raw values intact.
        "Boot consistency" to "启动状态一致性",
        "Boot parameters" to "启动参数",
        "Boot properties" to "启动属性",
        "Boot state" to "启动状态",
        "Boot raw" to "原始启动参数",
        "Verified boot" to "验证启动",
        "Certificate trust" to "证书信任",
        "Attestation chain" to "认证证书链",
        "Attestation tier" to "认证安全级别",
        "Attested boot state" to "认证的启动状态",
        "Lock state" to "锁定状态",
        "Properties checked" to "已检查属性",
        "Properties observed" to "已观察属性",
        "Rules checked" to "已检查规则",
        "Rules observed" to "已观察规则",
        "Cross-checks" to "交叉核验",
        "Cross-check rules" to "交叉核验规则",
        "Cross-source consistency" to "跨来源一致性",
        "Source mismatches" to "来源不一致",
        "Source consistency" to "来源一致性",
        "Raw boot hits" to "原始启动参数命中",
        "Native hits" to "原生检测命中",
        "Runtime hits" to "运行时命中",
        "Danger findings" to "危险发现",
        "Review findings" to "待核查发现",
        "Hard findings" to "高可信发现",
        "Info findings" to "参考信息",
        "Path hits" to "路径命中",
        "Paths checked" to "已检查路径",
        "Package visibility" to "应用可见性",
        "Packages checked" to "已检查应用",
        "Package catalog" to "应用目录",
        "Visible packages" to "可见应用",
        "Manager packages" to "管理器应用",
        "Module apps" to "模块应用",
        "Class hits" to "类命中",
        "ClassLoader hits" to "类加载器命中",
        "Binder hits" to "Binder 命中",
        "Logcat hits" to "日志命中",
        "Runtime artifacts" to "运行时痕迹",
        "Runtime artifact hits" to "运行时痕迹命中",
        "Runtime artifacts availability" to "运行时痕迹检查状态",
        "Dirty policy hits" to "策略异常命中",
        "Dirty policy availability" to "策略检查状态",
        "Native maps" to "原生内存映射",
        "Native heap" to "原生堆",
        "Native library" to "原生库",
        "Native traces" to "原生痕迹",
        "Native symbols" to "原生符号",
        "Native probes" to "原生探针",
        "Modified functions" to "被修改的函数",
        "Function hooks" to "函数 Hook",
        "Loader visibility" to "加载器可见性",
        "Signal handlers" to "信号处理器",
        "Threads and FDs" to "线程与文件描述符",
        "FD entries" to "文件描述符条目",
        "FD trap" to "FD 陷阱",
        "Cross-process FD trap" to "跨进程 FD 陷阱",
        "Mount namespace" to "挂载命名空间",
        "Mount entries" to "挂载条目",
        "Mountinfo entries" to "mountinfo 条目",
        "Mounts readable" to "挂载信息可读取",
        "Mountinfo readable" to "mountinfo 可读取",
        "Mount consistency" to "挂载一致性",
        "Cross-process mount views" to "跨进程挂载视图",
        "Isolated process mounts" to "隔离进程挂载",
        "Isolated mount drift" to "隔离进程挂载差异",
        "Mount drift hits" to "挂载差异命中",
        "Root artifacts" to "Root 痕迹",
        "Root processes" to "Root 进程",
        "Root daemons" to "Root 守护进程",
        "SU binaries" to "SU 可执行文件",
        "SU paths checked" to "已检查 SU 路径",
        "Proc contexts checked" to "已检查进程上下文",
        "Proc reads denied" to "进程信息读取被拒",
        "Self context" to "当前进程上下文",
        "Kernel identity" to "内核标识",
        "Kernel behavior" to "内核行为",
        "Kernel symbols" to "内核符号",
        "Kernel modules" to "内核模块",
        "Kernel sources" to "内核信息来源",
        "CVE patch state" to "CVE 修复状态",
        "Property residue" to "属性残留",
        "Property hits" to "属性命中",
        "Property catalog" to "属性目录",
        "Reflection hits" to "反射读取命中",
        "JVM hits" to "JVM 读取命中",
        "Native prop hits" to "原生属性命中",
        "Prop area anomalies" to "属性区异常",
        "Prop area holes" to "属性区空洞",
        "Full property audit" to "完整属性审计",
        "Transient skips" to "跳过的瞬时值",
        "Mismatched fields" to "不一致字段",
        "TEE Detailed Export" to "TEE 详细导出",
        "System properties" to "系统属性",
        "System filesystem type" to "系统文件系统类型",
        "Security classes" to "安全类别",
        "Permissive domains" to "宽松域",
        "SELinux policy" to "SELinux 策略",
        "Policy analysis" to "策略分析",
        "Policy version" to "策略版本",
        "Process context" to "进程上下文",
        "AVC side-channel" to "AVC 旁路信息",
        "Audit integrity" to "审计完整性",
        "Zygote permissions" to "Zygote 权限",
        "HMA mismatch" to "HMA 可见性不一致",
        "Environment hits" to "环境命中",
        "Translation hits" to "转译层命中",
        "Consistency hits" to "一致性检查命中",
        "Honeypot hits" to "蜜罐探针命中",
        "UID identity hits" to "UID 身份命中",
        "EGL renderer" to "EGL 渲染器",
        "Graphics renderer" to "图形渲染器",
        "Device IDs" to "设备标识",
        "Build profile" to "构建配置",
        "Properties and build" to "属性与构建信息",
        "Packages and modules" to "应用包与模块",
        "Binder and services" to "Binder 与服务",
        "Runtime markers" to "运行时痕迹",
    )

    private val countPatterns = listOf(
        Regex("""^(\d+) policy anomaly$""") to { m: MatchResult -> "${m.groupValues[1]} 项策略异常" },
        Regex("""^(\d+) policy review$""") to { m: MatchResult -> "${m.groupValues[1]} 项策略待核查" },
        Regex("""^(\d+) high-risk memory signal\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个高风险内存信号" },
        Regex("""^(\d+) high-risk LSPosed signal\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个高风险 LSPosed 信号" },
        Regex("""^(\d+) LSPosed residue signal\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个 LSPosed 残留信号" },
        Regex("""^(\d+) high-risk property or coherence signal\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个高风险属性或一致性信号" },
        Regex("""^(\d+) high-confidence residue signal\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个高可信残留信号" },
        Regex("""^(\d+) suspicious kernel signal\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个可疑内核信号" },
        Regex("""^(\d+) risky package\(s\) surfaced$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个风险应用包" },
        Regex("""^(\d+) direct virtualization signal\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个直接虚拟化信号" },
        Regex("""^(\d+) corroborating host app\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个相关宿主应用" },
        Regex("""^(\d+) runtime root signal\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个运行时 Root 信号" },
        Regex("""^(\d+) direct runtime signal\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个直接运行时信号" },
        Regex("""^(\d+) heuristic probes converged$""") to { m: MatchResult -> "${m.groupValues[1]} 项启发式探针指向同一异常" },
        Regex("""^(\d+) critical DRM consistency signal\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个严重 DRM 一致性信号" },
        Regex("""^(\d+) critical boot integrity signal\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个严重启动完整性信号" },
        Regex("""^(\d+) critical mount signal\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个严重挂载信号" },
        Regex("""^(\d+) critical startup signal\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个严重启动阶段信号" },
        Regex("""^(\d+) DRM consistency signal\(s\) need review$""") to { m: MatchResult -> "有 ${m.groupValues[1]} 个 DRM 一致性信号待核查" },
        Regex("""^(\d+) boot state signal\(s\) need review$""") to { m: MatchResult -> "有 ${m.groupValues[1]} 个启动状态信号待核查" },
        Regex("""^(\d+) mount signal\(s\) need review$""") to { m: MatchResult -> "有 ${m.groupValues[1]} 个挂载信号待核查" },
        Regex("""^(\d+) startup signal\(s\) need review$""") to { m: MatchResult -> "有 ${m.groupValues[1]} 个启动阶段信号待核查" },
        Regex("""^(\d+) native signal\(s\) need review$""") to { m: MatchResult -> "有 ${m.groupValues[1]} 个原生检测信号待核查" },
        Regex("""^(\d+) property signal\(s\) need review$""") to { m: MatchResult -> "有 ${m.groupValues[1]} 个属性信号待核查" },
        Regex("""^(\d+) virtualization signal\(s\) need review$""") to { m: MatchResult -> "有 ${m.groupValues[1]} 个虚拟化信号待核查" },
        Regex("""^(\d+) signal\(s\) need review$""") to { m: MatchResult -> "有 ${m.groupValues[1]} 个信号待核查" },
        Regex("""^(\d+) strong · (\d+) heuristic · (\d+) signal\(s\)$""") to { m: MatchResult ->
            "${m.groupValues[1]} 个强信号 · ${m.groupValues[2]} 个启发式信号 · ${m.groupValues[3]} 个总信号"
        },
        Regex("""^(\d+) mounts · (\d+) mountinfo · (\d+) map lines$""") to { m: MatchResult ->
            "${m.groupValues[1]} 个挂载条目 · ${m.groupValues[2]} 个 mountinfo 条目 · ${m.groupValues[3]} 行内存映射"
        },
        Regex("""^(\d+) props · (\d+) hits · (\d+) mismatch · (\d+) traces$""") to { m: MatchResult ->
            "${m.groupValues[1]} 项属性 · ${m.groupValues[2]} 个命中 · ${m.groupValues[3]} 处不一致 · ${m.groupValues[4]} 条痕迹"
        },
        Regex("""^(\d+) rules · (\d+) info · (\d+) native · (\d+) Build(?: · (\d+) prop-area hole\(s\))?$""") to { m: MatchResult ->
            "${m.groupValues[1]} 条规则 · ${m.groupValues[2]} 项信息 · ${m.groupValues[3]} 个原生命中 · ${m.groupValues[4]} 项构建信号" +
                m.groupValues[5].takeIf { it.isNotEmpty() }?.let { " · $it 个属性区域缺口" }.orEmpty()
        },
        Regex("""^(\d+) env · (\d+) translation · (\d+) runtime((?: · \d+ (?:dex|uid|trap hit\(s\)|host app\(s\)))*)$""") to { m: MatchResult ->
            val suffix = Regex(""" · (\d+) (dex|uid|trap hit\(s\)|host app\(s\))""")
                .replace(m.groupValues[4]) { part ->
                    val label = when (part.groupValues[2]) {
                        "dex" -> "DEX 路径"
                        "uid" -> "UID 标识"
                        "trap hit(s)" -> "陷阱命中"
                        else -> "宿主应用"
                    }
                    " · ${part.groupValues[1]} 个$label"
                }
            "${m.groupValues[1]} 个环境信号 · ${m.groupValues[2]} 个转译信号 · ${m.groupValues[3]} 个运行时信号$suffix"
        },
        Regex("""^(\d+) manager · (\d+) module · (\d+) native(?: · (\d+) policy)?$""") to { m: MatchResult ->
            "${m.groupValues[1]} 个管理器 · ${m.groupValues[2]} 个模块 · ${m.groupValues[3]} 条原生痕迹" +
                m.groupValues[4].takeIf { it.isNotEmpty() }?.let { " · $it 项策略信号" }.orEmpty()
        },
        Regex("""^(\d+) props · (\d+) mod props · (\d+) packages · (\d+) named services$""") to { m: MatchResult ->
            "${m.groupValues[1]} 项属性 · ${m.groupValues[2]} 项修改属性 · ${m.groupValues[3]} 个应用包 · ${m.groupValues[4]} 个命名服务"
        },
        Regex("""^(\d+) props · mod props unavailable · (\d+) packages · (\d+) named services$""") to { m: MatchResult ->
            "${m.groupValues[1]} 项属性 · 修改属性不可用 · ${m.groupValues[2]} 个应用包 · ${m.groupValues[3]} 个命名服务"
        },
        Regex("""^(\d+) legacy targets · (full|scoped) PM inventory(?: · (\d+) visible)?$""") to { m: MatchResult ->
            "${m.groupValues[1]} 个旧版目标 · ${if (m.groupValues[2] == "full") "完整" else "受限"}应用清单" +
                m.groupValues[3].takeIf { it.isNotEmpty() }?.let { " · $it 个可见" }.orEmpty()
        },
        Regex("""^(\d+) paths · (\d+) proc entries · (\d+) cgroup dirs · (\d+) kernel sources · (\d+) props$""") to { m: MatchResult ->
            "${m.groupValues[1]} 条路径 · ${m.groupValues[2]} 个进程条目 · ${m.groupValues[3]} 个 cgroup 目录 · ${m.groupValues[4]} 个内核来源 · ${m.groupValues[5]} 项属性"
        },
        Regex("""^(\d+) local device facts$""") to { m: MatchResult -> "${m.groupValues[1]} 项本机设备信息" },
        Regex("""^(\d+) su paths · (\d+) adb daemon paths · (native /proc scan|fallback self context)$""") to { m: MatchResult ->
            "${m.groupValues[1]} 条 su 路径 · ${m.groupValues[2]} 条 adb 守护进程路径 · ${if (m.groupValues[3] == "native /proc scan") "原生 /proc 扫描" else "备用自身上下文检查"}"
        },
        Regex("""^(\d+) keyword families · (\d+) cmdline rules · (native /proc|fallback file reads)$""") to { m: MatchResult ->
            "${m.groupValues[1]} 组关键词 · ${m.groupValues[2]} 条启动参数规则 · ${if (m.groupValues[3] == "native /proc") "原生 /proc 检查" else "备用文件读取"}"
        },
        Regex("""^7 local checks( \+ policy)?( \+ audit integrity \+ side-channel)?$""") to { m: MatchResult ->
            "7 项本地检查${if (m.groupValues[1].isNotEmpty()) " + 策略" else ""}${if (m.groupValues[2].isNotEmpty()) " + 审计完整性与旁路检查" else ""}"
        },
        Regex("""^(\d+) legacy targets$""") to { m: MatchResult -> "${m.groupValues[1]} 个旧版目标" },
        Regex("""^(\d+) legacy packages$""") to { m: MatchResult -> "${m.groupValues[1]} 个旧版应用包" },
        Regex("""^(\d+) su paths$""") to { m: MatchResult -> "已检查 ${m.groupValues[1]} 条 su 路径" },
        Regex("""^(\d+) hit\(s\)$""") to { m: MatchResult -> "${m.groupValues[1]} 个命中" },
        Regex("""^(\d+) view\(s\)$""") to { m: MatchResult -> "${m.groupValues[1]} 种视图" },
        Regex("""^(\d+) allowed$""") to { m: MatchResult -> "${m.groupValues[1]} 项允许" },
        Regex("""^(\d+) denied$""") to { m: MatchResult -> "${m.groupValues[1]} 项拒绝" },
        Regex("""^(\d+) unavailable$""") to { m: MatchResult -> "${m.groupValues[1]} 项不可用" },
        Regex("""^(\d+) critical (.+) signal\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个严重${translate(m.groupValues[2])}信号" },
        Regex("""^(\d+) (.+) signal\(s\) need review$""") to { m: MatchResult -> "有 ${m.groupValues[1]} 个${translate(m.groupValues[2])}信号待核查" },
        Regex("""^(\d+) (.+) signal\(s\)$""") to { m: MatchResult -> "发现 ${m.groupValues[1]} 个${translate(m.groupValues[2])}信号" },
        Regex("""^(\d+) props · (\d+) certs · (\d+) cross-checks$""") to { m: MatchResult ->
            "${m.groupValues[1]} 项属性 · ${m.groupValues[2]} 张证书 · ${m.groupValues[3]} 项交叉核验"
        },
        Regex("""^(\d+) of (\d+) .+""") to { m: MatchResult -> "${m.groupValues[1]} / ${m.groupValues[2]} 项已完成" },
    )

    fun translate(text: String): String {
        exact[text]?.let { return it }
        Regex("""^Local trust path: (.+), chain (verified|failed)(.*)$""").matchEntire(text)?.let {
            val chain = if (it.groupValues[2] == "verified") "已验证" else "验证失败"
            val suffix = it.groupValues[3]
                .replace("RKP observed on an invalid local chain", "在无效本地证书链上发现 RKP")
                .replace("RKP observed, local trust needs review", "发现 RKP，本地信任需要核查")
                .replace("RKP observed", "发现 RKP")
                .replace("provisioning needs review", "证书供应状态需要核查")
            return "本地信任路径：${it.groupValues[1]}，证书链${chain}${suffix}"
        }
        if (text.endsWith(" Attestation and trust-path checks still aligned.")) {
            val detail = text.removeSuffix(" Attestation and trust-path checks still aligned.")
            return "${translate(detail)} 认证与信任路径检查仍保持一致。"
        }
        Regex("""^(.+) daemon detected$""").matchEntire(text)?.let {
            return "检测到 ${it.groupValues[1]} 守护进程"
        }
        Regex("""^(\d+) package\(s\) were visible to direct corroboration probes but absent from PackageManager inventory\.$""")
            .matchEntire(text)?.let {
                return "有 ${it.groupValues[1]} 个应用包可被直接探针发现，却未出现在 PackageManager 清单中。"
            }
        Regex("""^Matched (\d+) package\(s\) across (\d+) category\(ies\)\. All package hits stay warning-level unless HMA concealment is present\.(.*)$""")
            .matchEntire(text)?.let {
                return "在 ${it.groupValues[2]} 个类别中命中 ${it.groupValues[1]} 个应用包。除非发现 HMA 隐藏，否则应用包命中仅计为警告。${it.groupValues[3]}"
            }
        if (text.startsWith("Scanned at ") && "\nTotal time " in text) {
            return text.replaceFirst("Scanned at ", "扫描时间：").replace("\nTotal time ", "\n总耗时：")
        }
        for ((pattern, replacement) in countPatterns) {
            pattern.matchEntire(text)?.let { return replacement(it) }
        }
        return text
    }
}
